import graphviz

g = graphviz.Digraph('flowchart', format='png')
g.attr(rankdir='TB', splines='ortho', nodesep='0.5', ranksep='0.45')
g.attr('node', fontname='Liberation Serif', fontsize='16')
g.attr('edge', fontname='Liberation Serif', fontsize='14')

g.node('start', 'Start', shape='ellipse', width='1.6', height='0.7')
g.node('upload', 'Upload Resume (PDF) +\nJob Description', shape='parallelogram', width='2.6', height='0.8')
g.node('extract', 'Extract Text (PyMuPDF)', shape='box', width='2.6', height='0.7')
g.node('extracted', 'Text\nExtracted?', shape='diamond', width='2.2', height='1.3')
g.node('embed', 'Generate Embeddings &\nStore in FAISS Vector DB', shape='box', width='2.8', height='0.8')
g.node('llm', 'Semantic Analysis using\nGemini 2.5 Flash', shape='box', width='2.8', height='0.8')
g.node('scores', 'Compute LLM Match Score &\nEmbedding Similarity Score', shape='box', width='2.9', height='0.8')
g.node('fuse', 'Fuse into Hybrid Match Score\nS = α·LLM + (1-α)·Embedding', shape='box', width='3.1', height='0.9', style='bold')
g.node('display', 'Display Results on\nInteractive Dashboard', shape='box', width='2.6', height='0.8')
g.node('query', 'User Asks\na Query?', shape='diamond', width='2.0', height='1.3')
g.node('rag', 'Retrieve Context (RAG)\nfrom FAISS + Gemini\nChatbot Response', shape='box', width='2.8', height='1.0')
g.node('stop', 'Stop', shape='ellipse', width='1.6', height='0.7')

g.edge('start', 'upload')
g.edge('upload', 'extract')
g.edge('extract', 'extracted')
g.edge('extracted', 'upload', label='no', constraint='false')
g.edge('extracted', 'embed', label='yes')
g.edge('embed', 'llm')
g.edge('llm', 'scores')
g.edge('scores', 'fuse')
g.edge('fuse', 'display')
g.edge('display', 'query')
g.edge('query', 'rag', label='yes')
g.edge('rag', 'display', constraint='false')
g.edge('query', 'stop', label='no')

out = g.render('fig1_flowchart_hybrid', cleanup=True)
print('rendered ->', out)
